import type { Metadata } from "next";
import { Inter } from "next/font/google";

import ProgressWrapper from "@/components/Wrapper/ProgressWrapper";

import "./globals.css";
import Link from "next/link";
import AppWrapper from "@/components/Wrapper/AppWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProgressWrapper>
          <AppWrapper>
            {children}
          </AppWrapper>
        </ProgressWrapper>
      </body>
    </html>
  );
}
